### ISSUE TITLE
Models Definition

### ISSUE THREAD

**Issue by adrian-pothuaud** [adrianpothuaud/NBAnalytics#27]
# Description
describe the issue below
- title
- short description
# Targets
describe targets below if necessary
- milestone
- release

**Comment by adrian-pothuaud** [comment]
http://mongoosejs.com/docs/models.html

**Comment by adrian-pothuaud** [comment]
Schemas OK
Models in progress
tests ???

**Comment by geo2fois** [comment]
je m'en occupe ce soir

**Comment by adrian-pothuaud** [comment]
tests failed

**Comment by adrian-pothuaud** [comment]
tests refactored and passed
